# Generated by Django 3.0.5 on 2021-01-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
