# Generated by Django 3.0.5 on 2021-01-04 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_auto_20210104_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
