# Generated by Django 3.0.5 on 2021-01-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_auto_20210105_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='Genero',
        ),
    ]
