# Generated by Django 3.0.5 on 2021-01-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0006_auto_20210105_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(default='Tecnico', max_length=500),
        ),
    ]
