# Generated by Django 3.0.5 on 2021-01-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0008_auto_20210105_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='Cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colaborador.Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='Genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colaborador.Genero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
